{{- if eq .Values.mode "server" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubesec.fullname" . }}
  labels:
    {{- include "kubesec.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kubesec.selectorLabels" . | nindent 4 }}
{{- end }}
