name: CI (Lint)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: helm-check
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./
        CHART_VALUES: ./values.yaml
